const countries = [
  {
    iso: "AF",
    englishName: "Afghanistan",
    name: "افغانستان",
    language: "Pashto",
  },
  {
    iso: "AL",
    englishName: "Albania",
    name: "Shqipërisë",
    language: "Albanian",
  },
  {
    iso: "DZ",
    englishName: "Algeria",
    name: "الجزائر",
    language: "Arabic",
  },
  {
    iso: "AM",
    englishName: "Armenia",
    name: "Հայաստան",
    language: "Armenian",
  },
  {
    iso: "AT",
    englishName: "Austria",
    name: "Österreich",
    language: "German",
  },
  {
    iso: "AZ",
    englishName: "Azerbaijan",
    name: "Azərbaycan",
    language: "Azerbaijani",
  },
  {
    iso: "BH",
    englishName: "Bahrain",
    name: "البحرين",
    language: "Arabic",
  },
  {
    iso: "BD",
    englishName: "Bangladesh",
    name: "বাংলাদেশ",
    language: "Bengali",
  },
  {
    iso: "BY",
    englishName: "Belarus",
    name: "Беларусь",
    language: "Belarusian",
  },
  {
    iso: "BE",
    englishName: "Belgium",
    name: "België",
    language: "Dutch",
  },
  {
    iso: "BT",
    englishName: "Bhutan",
    name: "འབྲུག་ཡུལ།",
    language: "Dzongkha",
  },
  {
    iso: "BA",
    englishName: "Bosnia and Herzegovina",
    name: "Bosna i Hercegovina",
    language: "Bosnian",
  },
  {
    iso: "BG",
    englishName: "Bulgaria",
    name: "България",
    language: "Bulgarian",
  },
  {
    iso: "KH",
    englishName: "Cambodia",
    name: "កម្ពុជា",
    language: "Khmer",
  },
  {
    iso: "CF",
    englishName: "Central African Republic",
    name: "Ködörösêse tî Bêafrîka",
    language: "Sango",
  },
  {
    iso: "TD",
    englishName: "Chad",
    name: "تشاد",
    language: "Arabic",
  },
  {
    iso: "CN",
    englishName: "China",
    name: "中国",
    language: "Chinese",
  },
  {
    iso: "KM",
    englishName: "Comoros",
    name: "Komori",
    language: "Comorian",
  },
  {
    iso: "HR",
    englishName: "Croatia",
    name: "Hrvatska",
    language: "Croatian",
  },
  {
    iso: "CY",
    englishName: "Cyprus",
    name: "Κύπρος",
    language: "Greek",
  },
  {
    iso: "CZ",
    englishName: "Czechia",
    name: "Česká republika",
    language: "Czech",
  },
  {
    iso: "DJ",
    englishName: "Djibouti",
    name: "جيبوتي",
    language: "Arabic",
  },
  {
    iso: "EG",
    englishName: "Egypt",
    name: "مصر",
    language: "Arabic",
  },
  {
    iso: "ER",
    englishName: "Eritrea",
    name: "ኤርትራ",
    language: "Tigrinya",
  },
  {
    iso: "EE",
    englishName: "Estonia",
    name: "Eesti",
    language: "Estonian",
  },
  {
    iso: "ET",
    englishName: "Ethiopia",
    name: "ኢትዮጵያ",
    language: "Amharic",
  },
  {
    iso: "FJ",
    englishName: "Fiji",
    name: "Viti",
    language: "Fijian",
  },
  {
    iso: "FI",
    englishName: "Finland",
    name: "Suomi",
    language: "Finnish",
  },
  {
    iso: "GE",
    englishName: "Georgia",
    name: "საქართველო",
    language: "Georgian",
  },
  {
    iso: "DE",
    englishName: "Germany",
    name: "Deutschland",
    language: "German",
  },
  {
    iso: "GR",
    englishName: "Greece",
    name: "Ελλάδα",
    language: "Greek",
  },
  {
    iso: "HT",
    englishName: "Haiti",
    name: "Ayiti",
    language: "Haitian Creole",
  },
  {
    iso: "HU",
    englishName: "Hungary",
    name: "Magyarország",
    language: "Hungarian",
  },
  {
    iso: "IS",
    englishName: "Iceland",
    name: "Ísland",
    language: "Icelandic",
  },
  {
    iso: "IN",
    englishName: "India",
    name: "भारत",
    language: "Hindi",
  },
  {
    iso: "IR",
    englishName: "Iran",
    name: "ایران",
    language: "Persian",
  },
  {
    iso: "IQ",
    englishName: "Iraq",
    name: "ٱلْعِرَاق",
    language: "Arabic",
  },
  {
    iso: "IE",
    englishName: "Ireland",
    name: "Éire",
    language: "Irish",
  },
  {
    iso: "IL",
    englishName: "Israel",
    name: "יִשְׂרָאֵל",
    language: "Hebrew",
  },
  {
    iso: "IT",
    englishName: "Italy",
  },
  {
    iso: "JP",
    englishName: "Japan",
    name: "日本",
    language: "Japanese",
  },
  {
    iso: "JO",
    englishName: "Jordan",
    name: "الأردن",
    language: "Arabic",
  },
  {
    iso: "KZ",
    englishName: "Kazakhstan",
    name: "Қазақстан",
    language: "Kazakh",
  },
  {
    iso: "KW",
    englishName: "Kuwait",
    name: "ٱلْكُوَيْت",
    language: "Arabic",
  },
  {
    iso: "KG",
    englishName: "Kyrgyzstan",
    name: "Кыргызстан",
    language: "Kyrgyz",
  },
  {
    iso: "LA",
    englishName: "Laos",
    name: "ສາທາລະນະລັດ ປະຊາທິປະໄຕ ປະຊາຊົນລາວ",
    language: "Lao",
  },
  {
    iso: "LV",
    englishName: "Latvia",
    name: "Latvijas",
    language: "Latvian",
  },
  {
    iso: "LB",
    englishName: "Lebanon",
    name: "لُبْنَان",
    language: "Arabic",
  },
  {
    iso: "LY",
    englishName: "Libya",
    name: "ليبيا",
    language: "Arabic",
  },
  {
    iso: "LT",
    englishName: "Lithuania",
    name: "Lietuva",
    language: "Lithuanian",
  },
  {
    iso: "LU",
    englishName: "Luxembourg",
    name: "Lëtzebuerg",
    language: "Luxembourgish",
  },
  {
    iso: "MV",
    englishName: "Maldives",
    name: "ދިވެހިރާއްޖެ",
    language: "Dhivehi",
  },
  {
    iso: "MH",
    englishName: "Marshall Islands",
    name: "Ṃajeḷ",
    language: "Marshallese",
  },
  {
    iso: "MR",
    englishName: "Mauritania",
    name: "موريتانيا",
    language: "Arabic",
  },
  {
    iso: "MU",
    englishName: "Mauritius",
    name: "Maurice",
    language: "French",
  },
  {
    iso: "MN",
    englishName: "Mongolia",
    name: "Монгол Улс",
    language: "Mongolian",
  },
  {
    iso: "ME",
    englishName: "Montenegro",
    name: "Crna Gora",
    language: "Montenegrin",
  },
  {
    iso: "MA",
    englishName: "Morocco",
    name: "المغرب",
    language: "Arabic",
  },
  {
    iso: "MM",
    englishName: "Myanmar",
    name: "မြန်မာ",
    language: "Burmese",
  },
  {
    iso: "NP",
    englishName: "Nepal",
    name: "नेपाल",
    language: "Nepali",
  },
  {
    iso: "NZ",
    englishName: "New Zealand",
    name: "Aotearoa",
    language: "Māori",
  },
  {
    iso: "NE",
    englishName: "Niger",
    name: "Nijar",
    language: "Hausa",
  },
  {
    iso: "KP",
    englishName: "North Korea",
    name: "조선",
    language: "Korean",
  },
  {
    iso: "MK",
    englishName: "North Macedonia",
    name: "Северна Македонија",
    language: "Macedonian",
  },
  {
    iso: "NO",
    englishName: "Norway",
    name: "Norge",
    language: "Norwegian",
  },
  {
    iso: "OM",
    englishName: "Oman",
    name: "عُمَان",
    language: "Arabic",
  },
  {
    iso: "PK",
    englishName: "Pakistan",
    name: "پَاکِسْتَان",
    language: "Urdu",
  },
  {
    iso: "PW",
    englishName: "Palau",
    name: "Belau",
    language: "Palauan",
  },
  {
    iso: "PS",
    englishName: "Palestine",
    name: "فلسطين",
    language: "Arabic",
  },
  {
    iso: "PH",
    englishName: "Philippines",
    name: "Pilipinas",
    language: "Filipino",
  },
  {
    iso: "PL",
    englishName: "Poland",
    name: "Polska",
    language: "Polish",
  },
  {
    iso: "PT",
    englishName: "Portugal",
  },
  {
    iso: "QA",
    englishName: "Qatar",
    name: "قطر",
    language: "Arabic",
  },
  {
    iso: "RU",
    englishName: "Russia",
    name: "Россия",
    language: "Russian",
  },
  {
    iso: "SA",
    englishName: "Saudi Arabia",
    name: "ٱلسُّعُودِيَّة",
    language: "Arabic",
  },
  {
    iso: "RS",
    englishName: "Serbia",
    name: "Србија",
    language: "Serbian",
  },
  {
    iso: "SL",
    englishName: "Sierra Leone",
    name: "Salone",
    language: "Krio",
  },
  {
    iso: "SK",
    englishName: "Slovakia",
    name: "Slovensko",
    language: "Slovak",
  },
  {
    iso: "SO",
    englishName: "Somalia",
    name: "Soomaaliya",
    language: "Somali",
  },
  {
    iso: "KR",
    englishName: "South Korea",
    name: "한국",
    language: "Korean",
  },
  {
    iso: "ES",
    englishName: "Spain",
    name: "España",
    language: "Spanish",
  },
  {
    iso: "LK",
    englishName: "Sri Lanka",
    name: "ශ්‍රී ලංකා",
    language: "Sinhala",
  },
  {
    iso: "SD",
    englishName: "Sudan",
    name: "السودان",
    language: "Arabic",
  },
  {
    iso: "SE",
    englishName: "Sweden",
    name: "Sverige",
    language: "Swedish",
  },
  {
    iso: "CH",
    englishName: "Switzerland",
    name: "Schweiz",
    language: "German",
  },
  {
    iso: "SY",
    englishName: "Syria",
    name: "سُورِيَة",
    language: "Arabic",
  },
  {
    iso: "TJ",
    englishName: "Tajikistan",
    name: "Тоҷикистон",
    language: "Tajik",
  },
  {
    iso: "TH",
    englishName: "Thailand",
    name: "ประเทศไทย",
    language: "Thai",
  },
  {
    iso: "TN",
    englishName: "Tunisia",
    name: "تونس",
    language: "Arabic",
  },
  {
    iso: "UA",
    englishName: "Ukraine",
    name: "Україна",
    language: "Ukrainian",
  },
  {
    iso: "AE",
    englishName: "United Arab Emirates",
    name: "الإمارات العربيّة المتّحدة",
    language: "Arabic",
  },
  {
    iso: "UZ",
    englishName: "Uzbekistan",
    name: "O‘zbekiston",
    language: "Uzbek",
  },
  {
    iso: "YE",
    englishName: "Yemen",
    name: "ٱلْيَمَنْ",
    language: "Arabic",
  },
];
