const anthems = [
  {
    iso: "AL",
    countryName: "Albania",
    anthemName: "Himni i Flamurit",
    src: "https://www.navyband.navy.mil/music/anthems/albania.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Hymn to the Flag",
  },
  {
    iso: "DZ",
    countryName: "Algeria",
    anthemName: "قَسَمًا",
    src: "https://www.navyband.navy.mil/music/anthems/algeria.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "We Pledge",
  },
  {
    iso: "AD",
    countryName: "Andorra",
    anthemName: "El gran Carlemany",
    src: "https://upload.wikimedia.org/wikipedia/commons/5/5b/El_Gran_Carlemany.ogg",
    attribution: {
      text: "Government of Andorra",
      href: "https://commons.wikimedia.org/wiki/File:El_Gran_Carlemany.ogg",
    },
    translatedName: "The Great Charlemagne",
  },
  {
    iso: "AO",
    countryName: "Angola",
    anthemName: "Angola Avante",
    src: "https://www.navyband.navy.mil/music/anthems/angola.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Onwards Angola",
  },
  {
    iso: "AG",
    countryName: "Antigua and Barbuda",
    anthemName: "Fair Antigua, We Salute Thee",
    src: "https://www.navyband.navy.mil/music/anthems/antigua-and-barbuda.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
  },
  {
    iso: "AR",
    countryName: "Argentina",
    anthemName: "Himno Nacional Argentino",
    src: "https://www.navyband.navy.mil/music/anthems/argentina-short.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Argentine National Anthem",
  },
  {
    iso: "AM",
    countryName: "Armenia",
    anthemName: "Mer Hayrenik",
    src: "https://www.navyband.navy.mil/music/anthems/armenia.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Our Fatherland",
  },
  {
    iso: "AU",
    countryName: "Australia",
    anthemName: "Advance Australia Fair",
    src: "https://www.navyband.navy.mil/music/anthems/australia-complete.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
  },
  {
    iso: "AT",
    countryName: "Austria",
    anthemName: "Bundeshymne der Republik Österreich",
    src: "https://www.navyband.navy.mil/music/anthems/austria.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "National Anthem of the Republic of Austria",
  },
  {
    iso: "AZ",
    countryName: "Azerbaijan",
    anthemName: "Azərbaycan Respublikasının Dövlət Himni",
    src: "https://www.navyband.navy.mil/music/anthems/azerbaijan.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "State Anthem of the Republic of Azerbaijan",
  },
  {
    iso: "BH",
    countryName: "Bahrain",
    anthemName: "بحريننا",
    src: "https://www.navyband.navy.mil/music/anthems/bahrain.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Our Bahrain",
  },
  {
    iso: "BD",
    countryName: "Bangladesh",
    anthemName: "আমার সোনার বাংলা",
    src: "https://www.navyband.navy.mil/music/anthems/bangladesh.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "My Golden Bengal",
  },
  {
    iso: "BB",
    countryName: "Barbados",
    anthemName: "In Plenty and In Time of Need",
    src: "https://www.navyband.navy.mil/music/anthems/barbados.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
  },
  {
    iso: "BY",
    countryName: "Belarus",
    anthemName: "Дзяржаўны гімн Рэспублікі Беларусь",
    src: "https://web.archive.org.au/awa/20231218155154mp_/https://www.navy.gov.au/sites/default/files/audio/Belarus.mp3",
    attribution: {
      text: "Royal Australian Navy Band",
      href: "https://webarchive.nla.gov.au/awa/20231218155154/https://www.navy.gov.au/global-anthems",
    },
    translatedName: "State Anthem of the Republic of Belarus",
  },
  {
    iso: "BE",
    countryName: "Belgium",
    anthemName: "La Brabançonne",
    src: "https://www.navyband.navy.mil/music/anthems/belgium.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "The Brabantian",
  },
  {
    iso: "BZ",
    countryName: "Belize",
    anthemName: "Land of the Free",
    src: "https://www.navyband.navy.mil/music/anthems/belize.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
  },
  {
    iso: "BJ",
    countryName: "Benin",
    anthemName: "L'Aube nouvelle",
    src: "https://www.navyband.navy.mil/music/anthems/benin.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "The Dawn of a New Day",
  },
  {
    iso: "BT",
    countryName: "Bhutan",
    anthemName: "འབྲུག་ཙན་དན",
    src: "https://nationalanthems.info/bt.mp3",
    attribution: {
      text: "Keith Terrett / nationalanthems.info",
      href: "https://nationalanthems.info/bt.htm",
    },
    translatedName: "The Thunder Dragon Kingdom",
  },
  {
    iso: "BO",
    countryName: "Bolivia",
    anthemName: "Himno Nacional de Bolivia",
    src: "https://www.navyband.navy.mil/music/anthems/bolivia.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "National Anthem of Bolivia",
  },
  {
    iso: "BA",
    countryName: "Bosnia and Herzegovina",
    anthemName: "Državna himna Bosne i Hercegovine",
    src: "https://www.navyband.navy.mil/music/anthems/bosnia-herzegovina.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "National Anthem of Bosnia and Herzegovina",
  },
  {
    iso: "BW",
    countryName: "Botswana",
    anthemName: "Fatshe leno la rona",
    src: "https://www.navyband.navy.mil/music/anthems/botswana.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Blessed Be This Noble Land",
  },
  {
    iso: "BR",
    countryName: "Brazil",
    anthemName: "Hino Nacional Brasileiro",
    src: "https://www.navyband.navy.mil/music/anthems/brazil.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Brazilian National Anthem",
  },
  {
    iso: "BN",
    countryName: "Brunei",
    anthemName: "الله ڤليهاراكن سلطان",
    src: "https://www.navyband.navy.mil/music/anthems/brunei.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "God Bless the Sultan",
  },
  {
    iso: "BG",
    countryName: "Bulgaria",
    anthemName: "Мила Родино",
    src: "https://www.navyband.navy.mil/music/anthems/bulgaria-short.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Dear Motherland",
  },
  {
    iso: "BF",
    countryName: "Burkina Faso",
    anthemName: "Le Ditanyè",
    src: "https://www.navyband.navy.mil/music/anthems/burkina-faso.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "The Anthem of Victory",
  },
  {
    iso: "BI",
    countryName: "Burundi",
    anthemName: "Burundi Bwacu",
    src: "https://nationalanthems.info/bi.mp3",
    attribution: {
      text: "Keith Terrett / nationalanthems.info",
      href: "https://nationalanthems.info/bi.htm",
    },
    translatedName: "Our Burundi",
  },
  {
    iso: "CV",
    countryName: "Cabo Verde",
    anthemName: "Cântico da Liberdade",
    src: "https://www.navyband.navy.mil/music/anthems/cape-verde.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Chant of Liberty",
  },
  {
    iso: "KH",
    countryName: "Cambodia",
    anthemName: "នគររាជ",
    src: "https://www.navyband.navy.mil/music/anthems/cambodia.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Majestic Kingdom",
  },
  {
    iso: "CM",
    countryName: "Cameroon",
    anthemName: "Chant de Ralliement",
    src: "https://www.navyband.navy.mil/music/anthems/cameroon.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "The Rallying Song",
  },
  {
    iso: "CA",
    countryName: "Canada",
    anthemName: "O Canada",
    src: "https://upload.wikimedia.org/wikipedia/commons/0/0a/%22O_Canada%22-%C2%AB%C3%94_Canada%C2%BB%2C_performed_by_the_National_Band_of_the_Naval_Reserve.oga",
    attribution: {
      text: "National Band of the Naval Reserve",
      href: "https://commons.wikimedia.org/wiki/File:%22O_Canada%22-%C2%AB%C3%94_Canada%C2%BB,_performed_by_the_National_Band_of_the_Naval_Reserve.oga",
    },
  },
  {
    iso: "CF",
    countryName: "Central African Republic",
    anthemName: "La Renaissance",
    src: "https://www.navyband.navy.mil/music/anthems/central-african-republic.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "The Renaissance",
  },
  {
    iso: "TD",
    countryName: "Chad",
    anthemName: "La Tchadienne",
    src: "https://www.navyband.navy.mil/music/anthems/chad.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Song of the Chadian",
  },
  {
    iso: "CL",
    countryName: "Chile",
    anthemName: "Himno Nacional de Chile",
    src: "https://www.navyband.navy.mil/music/anthems/chile.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "National Anthem of Chile",
  },
  {
    iso: "CN",
    countryName: "China",
    anthemName: "义勇军进行曲",
    src: "https://upload.wikimedia.org/wikipedia/commons/9/95/%E3%80%8A%E4%B8%AD%E5%8D%8E%E4%BA%BA%E6%B0%91%E5%85%B1%E5%92%8C%E5%9B%BD%E5%9B%BD%E6%AD%8C%E3%80%8B%E5%AE%98%E6%96%B9%E5%BD%95%E9%9F%B3%E7%89%88%E6%9C%AC%EF%BC%88%E7%AE%A1%E4%B9%90%E7%89%88%EF%BC%89.wav",
    attribution: {
      text: "State Council of China",
      href: "https://commons.wikimedia.org/wiki/File:%E3%80%8A%E4%B8%AD%E5%8D%8E%E4%BA%BA%E6%B0%91%E5%85%B1%E5%92%8C%E5%9B%BD%E5%9B%BD%E6%AD%8C%E3%80%8B%E5%AE%98%E6%96%B9%E5%BD%95%E9%9F%B3%E7%89%88%E6%9C%AC%EF%BC%88%E7%AE%A1%E4%B9%90%E7%89%88%EF%BC%89.wav",
    },
    translatedName: "March of the Volunteers",
  },
  {
    iso: "CO",
    countryName: "Colombia",
    anthemName: "Himno Nacional de la República de Colombia",
    src: "https://www.navyband.navy.mil/music/anthems/colombia.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "National Anthem of the Republic of Colombia",
  },
  {
    iso: "KM",
    countryName: "Comoros",
    anthemName: "Udzima wa ya Masiwa",
    src: "https://www.navyband.navy.mil/music/anthems/comoros.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "The Union of the Great Islands",
  },
  {
    iso: "CR",
    countryName: "Costa Rica",
    anthemName: "Himno Nacional de la República de Costa Rica",
    src: "www.navyband.navy.mil/music/anthems/costa-rica.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "National Anthem of the Republic of Costa Rica",
  },
  {
    iso: "HR",
    countryName: "Croatia",
    anthemName: "Lijepa naša domovino",
    src: "https://www.navyband.navy.mil/music/anthems/croatia.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Our Beautiful Homeland",
  },
  {
    iso: "CU",
    countryName: "Cuba",
    anthemName: "La Bayamesa",
    src: "https://upload.wikimedia.org/wikipedia/commons/b/b8/Cuba_National_Anthem_Instrumental.ogg",
    attribution: {
      text: "Government of Cuba",
      href: "https://commons.wikimedia.org/wiki/File:Cuba_National_Anthem_Instrumental.ogg",
    },
    translatedName: "The Bayamo Anthem",
  },
  {
    iso: "CZ",
    countryName: "Czechia",
    anthemName: "Kde domov můj",
    src: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Czech_anthem.ogg",
    attribution: {
      text: "Prague National Theatre Orchestra",
      href: "https://commons.wikimedia.org/wiki/File:Czech_anthem.ogg",
    },
    translatedName: "Where My Home Is",
  },
  {
    iso: "CD",
    countryName: "Democratic Republic of the Congo",
    anthemName: "Debout Congolais",
    src: "https://www.navyband.navy.mil/music/anthems/congo.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Arise Congolese",
  },
  {
    iso: "DK",
    countryName: "Denmark",
    anthemName: "Der er et yndigt land",
    src: "https://www.navyband.navy.mil/music/anthems/denmark-national-anthem.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "There Is a Lovely Land",
  },
  {
    iso: "DJ",
    countryName: "Djibouti",
    anthemName: "Djibouti",
    src: "https://www.navyband.navy.mil/music/anthems/djibouti.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
  },
  {
    iso: "DM",
    countryName: "Dominica",
    anthemName: "Isle of Beauty, Isle of Splendour",
    src: "https://www.navyband.navy.mil/music/anthems/dominica.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
  },
  {
    iso: "DO",
    countryName: "Dominican Republic",
    anthemName: "Himno nacional de República Dominicana",
    src: "https://www.navyband.navy.mil/music/anthems/dominican-republic.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "National Anthem of the Dominican Republic",
  },
  {
    iso: "EC",
    countryName: "Ecuador",
    anthemName: "¡Salve, Oh Patria!",
    src: "https://upload.wikimedia.org/wikipedia/commons/c/c5/Ecuadorian_national_anthem_%28abridged%29.ogg",
    attribution: {
      text: "United States Navy Band",
      href: "https://commons.wikimedia.org/wiki/File:Ecuadorian_national_anthem_(abridged).ogg",
    },
    translatedName: "Hail, Oh Fatherland!",
  },
  {
    iso: "EG",
    countryName: "Egypt",
    anthemName: "بلادي بلادي بلادي",
    src: "https://www.navyband.navy.mil/music/anthems/egypt.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "My homeland, my homeland, my homeland",
  },
  {
    iso: "SV",
    countryName: "El Salvador",
    anthemName: "Himno Nacional de El Salvador",
    src: "https://upload.wikimedia.org/wikipedia/commons/6/6a/El_Salvador%27s_national_anthem_%28abridged%29.ogg",
    attribution: {
      text: "United States Navy Band",
      href: "https://commons.wikimedia.org/wiki/File:El_Salvador%27s_national_anthem_(abridged).ogg",
    },
    translatedName: "National Anthem of El Salvador",
  },
  {
    iso: "GQ",
    countryName: "Equatorial Guinea",
    anthemName: "Caminemos pisando las sendas de nuestra inmensa felicidad",
    src: "https://upload.wikimedia.org/wikipedia/commons/2/2c/Equatorial_Guinea%27s_national_anthem%2C_performed_by_the_United_States_Navy_Band.oga",
    attribution: {
      text: "United States Navy Band",
      href: "https://commons.wikimedia.org/wiki/File:Equatorial_Guinea%27s_national_anthem,_performed_by_the_United_States_Navy_Band.oga",
    },
    translatedName: "Let Us Walk Treading the Paths of Our Immense Happiness",
  },
  {
    iso: "ER",
    countryName: "Eritrea",
    anthemName: "ኤርትራ ኤርትራ ኤርትራ",
    src: "https://www.navyband.navy.mil/music/anthems/eritrea.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Eritrea, Eritrea, Eritrea",
  },
  {
    iso: "EE",
    countryName: "Estonia",
    anthemName: "Mu isamaa, mu õnn ja rõõm",
    src: "https://www.navyband.navy.mil/music/anthems/estonia.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "My Fatherland, My Happiness and Joy",
  },
  {
    iso: "SZ",
    countryName: "Eswatini",
    anthemName: "Nkulunkulu Mnikati wetibusiso temaSwati",
    src: "https://www.navyband.navy.mil/music/anthems/swaziland.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "God, the Giver of blessings to the Swati people",
  },
  {
    iso: "ET",
    countryName: "Ethiopia",
    anthemName: "ወደፊት ገስግሺ ውድ እናት ኢትዮጵያ",
    src: "https://www.navyband.navy.mil/music/anthems/ethiopia.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "March Forward, Dear Mother Ethiopia",
  },
  {
    iso: "FJ",
    countryName: "Fiji",
    anthemName: "Meda dau doka",
    src: "https://www.navyband.navy.mil/music/anthems/fiji.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "God Bless Fiji",
  },
  {
    iso: "FI",
    countryName: "Finland",
    anthemName: "Maamme",
    src: "https://www.navyband.navy.mil/music/anthems/finland.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Our Land",
  },
  {
    iso: "FR",
    countryName: "France",
    anthemName: "La Marseillaise",
    src: "https://www.navyband.navy.mil/music/anthems/france.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "The Song of Marseille",
  },
  {
    iso: "GA",
    countryName: "Gabon",
    anthemName: "La Concorde",
    src: "https://www.navyband.navy.mil/music/anthems/gabon.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "The Concorde",
  },
  {
    iso: "GE",
    countryName: "Georgia",
    anthemName: "თავისუფლება",
    src: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Tavisupleba_instrumental.ogg",
    attribution: {
      text: "President of Georgia",
      href: "https://commons.wikimedia.org/wiki/File:Tavisupleba_instrumental.ogg",
    },
    translatedName: "Freedom",
  },
  {
    iso: "DE",
    countryName: "Germany",
    anthemName: "Deutschlandlied",
    src: "https://www.navyband.navy.mil/music/anthems/germany.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Germany Song",
  },
  {
    iso: "GH",
    countryName: "Ghana",
    anthemName: "God Bless Our Homeland Ghana",
    src: "https://www.navyband.navy.mil/music/anthems/ghana.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
  },
  {
    iso: "GR",
    countryName: "Greece",
    anthemName: "Ύμνος εις την Ελευθερίαν",
    src: "https://www.navyband.navy.mil/music/anthems/greece.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Hymn to Liberty",
  },
  {
    iso: "GD",
    countryName: "Grenada",
    anthemName: "Hail Grenada",
    src: "https://web.archive.org.au/awa/20231218155154mp_/https://www.navy.gov.au/sites/default/files/audio/Grenada.mp3",
    attribution: {
      text: "Royal Australian Navy Band",
      href: "https://webarchive.nla.gov.au/awa/20231218155154/https://www.navy.gov.au/global-anthems",
    },
  },
  {
    iso: "GT",
    countryName: "Guatemala",
    anthemName: "Himno Nacional de Guatemala",
    src: "https://www.navyband.navy.mil/music/anthems/guatemala.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "National Anthem of Guatemala",
  },
  {
    iso: "GN",
    countryName: "Guinea",
    anthemName: "Liberté",
    src: "https://www.navyband.navy.mil/music/anthems/guinea.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Freedom",
  },
  {
    iso: "GW",
    countryName: "Guinea-Bissau",
    anthemName: "Esta É a Nossa Pátria Bem Amada",
    src: "https://www.navyband.navy.mil/music/anthems/guinea-bissau.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "This Is Our Well Beloved Fatherland",
  },
  {
    iso: "GY",
    countryName: "Guyana",
    anthemName: "Green Land of Guyana",
    src: "https://www.navyband.navy.mil/music/anthems/guyana.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
  },
  {
    iso: "HT",
    countryName: "Haiti",
    anthemName: "La Dessalinienne",
    src: "https://www.navyband.navy.mil/music/anthems/haiti.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "The Dessaline",
  },
  {
    iso: "HN",
    countryName: "Honduras",
    anthemName: "Himno Nacional de Honduras",
    src: "https://www.navyband.navy.mil/music/anthems/honduras.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "National Anthem of Honduras",
  },
  {
    iso: "HU",
    countryName: "Hungary",
    anthemName: "Himnusz",
    src: "https://www.navyband.navy.mil/music/anthems/hungary.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Anthem",
  },
  {
    iso: "IS",
    countryName: "Iceland",
    anthemName: "Lofsöngur",
    src: "https://www.navyband.navy.mil/music/anthems/iceland.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Hymn",
  },
  {
    iso: "IN",
    countryName: "India",
    anthemName: "Jana Gana Mana",
    src: "https://www.navyband.navy.mil/music/anthems/india.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "The Minds of All People",
  },
  {
    iso: "ID",
    countryName: "Indonesia",
    anthemName: "Indonesia Raya",
    src: "https://www.navyband.navy.mil/music/anthems/indonesia.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Indonesia the Great",
  },
  {
    iso: "IR",
    countryName: "Iran",
    anthemName: "سرود ملی جمهوری اسلامی ایران",
    src: "https://upload.wikimedia.org/wikipedia/commons/f/f2/Sorud-e_Mell%C3%AD-e_Yomhur%C3%AD-e_Eslam%C3%AD-e_Ir%C3%A1n_%28instrumental%29.oga",
    attribution: {
      text: "Government of Islamic Republic of Iran",
      href: "https://commons.wikimedia.org/wiki/File:Sorud-e_Mell%C3%AD-e_Yomhur%C3%AD-e_Eslam%C3%AD-e_Ir%C3%A1n_(instrumental).oga",
    },
    translatedName: "National Anthem of the Islamic Republic of Iran",
  },
  {
    iso: "IQ",
    countryName: "Iraq",
    anthemName: "موطني",
    src: "https://www.navyband.navy.mil/music/anthems/iraq.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "My Homeland",
  },
  {
    iso: "IE",
    countryName: "Ireland",
    anthemName: "Amhrán na bhFiann",
    src: "https://www.navyband.navy.mil/music/anthems/ireland.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "The Soldier's Song",
  },
  {
    iso: "IL",
    countryName: "Israel",
    anthemName: "הַתִּקְוָה‎",
    src: "https://www.navyband.navy.mil/music/anthems/israel.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "The Hope",
  },
  {
    iso: "IT",
    countryName: "Italy",
    anthemName: "Il Canto degli Italiani",
    src: "https://www.navyband.navy.mil/music/anthems/italy-complete.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "The Song of the Italians",
  },
  {
    iso: "CI",
    countryName: "Ivory Coast",
    anthemName: "L'Abidjanaise",
    src: "https://www.navyband.navy.mil/music/anthems/cote-divoire.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "The Song of Abidjan",
  },
  {
    iso: "JM",
    countryName: "Jamaica",
    anthemName: "Jamaica, Land We Love",
    src: "https://www.navyband.navy.mil/music/anthems/jamaica.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
  },
  {
    iso: "JP",
    countryName: "Japan",
    anthemName: "君が代",
    src: "https://www.navyband.navy.mil/music/anthems/japan.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "His Imperial Majesty's Reign",
  },
  {
    iso: "JO",
    countryName: "Jordan",
    anthemName: "السلام الملكي الأردني",
    src: "https://www.navyband.navy.mil/music/anthems/jordan.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Peace be upon the King of Jordan",
  },
  {
    iso: "KZ",
    countryName: "Kazakhstan",
    anthemName: "Менің Қазақстаным",
    src: "https://www.navyband.navy.mil/music/anthems/kazakhstan.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "My Kazakhstan",
  },
  {
    iso: "KE",
    countryName: "Kenya",
    anthemName: "Ee Mungu Nguvu Yetu",
    src: "https://www.navyband.navy.mil/music/anthems/kenya.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "O God of all Creation",
  },
  {
    iso: "KI",
    countryName: "Kiribati",
    anthemName: "Kunan Kiribati",
    src: "https://upload.wikimedia.org/wikipedia/commons/2/20/Kiribati_Anthem_Performed_by_US_Navy_Band.oga",
    attribution: {
      text: "United States Navy Band",
      href: "https://commons.wikimedia.org/wiki/File:Kiribati_Anthem_Performed_by_US_Navy_Band.oga",
    },
    translatedName: "Song of Kiribati",
  },
  {
    iso: "XK",
    countryName: "Kosovo",
    anthemName: "Himni i Republikës së Kosovës",
    src: "https://www.navyband.navy.mil/music/anthems/kosovo.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Anthem of the Republic of Kosovo",
  },
  {
    iso: "KW",
    countryName: "Kuwait",
    anthemName: "النشيد الوطني الكويتي",
    src: "https://www.navyband.navy.mil/music/anthems/kuwait.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "The National Anthem",
  },
  {
    iso: "KG",
    countryName: "Kyrgyzstan",
    anthemName: "Кыргыз Республикасынын Мамлекеттик гимни",
    src: "https://upload.wikimedia.org/wikipedia/commons/9/9d/National_anthem_of_Kyrgyzstan_%28instrumental%29.ogg",
    attribution: {
      text: "Government of Kyrgyzstan",
      href: "https://commons.wikimedia.org/wiki/File:National_anthem_of_Kyrgyzstan_(instrumental).ogg",
    },
    translatedName: "National Anthem of the Kyrgyz Republic",
  },
  {
    iso: "LA",
    countryName: "Laos",
    anthemName: "ເພງຊາດລາວ",
    src: "https://www.navyband.navy.mil/music/anthems/laos.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Lao National Anthem",
  },
  {
    iso: "LV",
    countryName: "Latvia",
    anthemName: "Dievs, svētī Latviju!",
    src: "https://upload.wikimedia.org/wikipedia/commons/d/d1/NBS_%C5%A0t%C4%81ba_or%C4%B7estris_-_Dievs%2C_sv%C4%93t%C4%AB_Latviju%21.ogg",
    attribution: {
      text: "Latvian Army Orchestra",
      href: "https://commons.wikimedia.org/wiki/File:NBS_%C5%A0t%C4%81ba_or%C4%B7estris_-_Dievs,_sv%C4%93t%C4%AB_Latviju!.ogg",
    },
    translatedName: "God Bless Latvia!",
  },
  {
    iso: "LB",
    countryName: "Lebanon",
    anthemName: "النشيد الوطني اللبناني",
    src: "https://www.navyband.navy.mil/music/anthems/lebanon.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Lebanese National Anthem",
  },
  {
    iso: "LS",
    countryName: "Lesotho",
    anthemName: "Lesōthō Fatše La Bo-Ntat'a Rōna",
    src: "https://www.navyband.navy.mil/music/anthems/lesotho.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Lesotho, Land of Our Fathers",
  },
  {
    iso: "LR",
    countryName: "Liberia",
    anthemName: "All Hail, Liberia, Hail!",
    src: "https://www.navyband.navy.mil/music/anthems/liberia.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
  },
  {
    iso: "LY",
    countryName: "Libya",
    anthemName: "ليبيا ليبيا ليبيا",
    src: "https://www.navyband.navy.mil/music/anthems/libya.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Libya, Libya, Libya",
  },
  {
    iso: "LT",
    countryName: "Lithuania",
    anthemName: "Tautiška giesmė",
    src: "https://www.navyband.navy.mil/music/anthems/lithuania.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "National Song",
  },
  {
    iso: "LU",
    countryName: "Luxembourg",
    anthemName: "Ons Heemecht",
    src: "https://www.navyband.navy.mil/music/anthems/luxembourg.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Our Homeland",
  },
  {
    iso: "MG",
    countryName: "Madagascar",
    anthemName: "Ry Tanindrazanay malala ô!",
    src: "https://www.navyband.navy.mil/music/anthems/macedonia.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Oh, beloved land of our ancestors!",
  },
  {
    iso: "MW",
    countryName: "Malawi",
    anthemName: "Mlungu dalitsani Malaŵi",
    src: "https://www.navyband.navy.mil/music/anthems/malawi.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "O God bless our land of Malawi",
  },
  {
    iso: "MY",
    countryName: "Malaysia",
    anthemName: "Negaraku",
    src: "https://www.navyband.navy.mil/music/anthems/malaysia-long.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "My Country",
  },
  {
    iso: "MV",
    countryName: "Maldives",
    anthemName: "ޤައުމީ ސަލާމް",
    src: "https://www.navyband.navy.mil/music/anthems/maldives.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "National Salute",
  },
  {
    iso: "ML",
    countryName: "Mali",
    anthemName: "Le Mali",
    src: "https://www.navyband.navy.mil/music/anthems/mali.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "The Mali",
  },
  {
    iso: "MT",
    countryName: "Malta",
    anthemName: "L-Innu Malti",
    src: "https://www.navyband.navy.mil/music/anthems/malta.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "The Maltese Hymn",
  },
  {
    iso: "MH",
    countryName: "Marshall Islands",
    anthemName: "Indeeo Ṃajeḷ",
    src: "https://www.navyband.navy.mil/music/anthems/marshall-islands.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Forever Marshall Islands",
  },
  {
    iso: "MR",
    countryName: "Mauritania",
    anthemName: "النشيد الوطني الموريتاني",
    src: "https://www.navyband.navy.mil/music/anthems/mauritania.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "National anthem of Mauritania",
  },
  {
    iso: "MU",
    countryName: "Mauritius",
    anthemName: "Motherland",
    src: "https://www.navyband.navy.mil/music/anthems/mauritius.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
  },
  {
    iso: "MX",
    countryName: "Mexico",
    anthemName: "Himno Nacional Mexicano",
    src: "https://www.navyband.navy.mil/music/anthems/mexico.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Mexican National Anthem",
  },
  {
    iso: "FM",
    countryName: "Micronesia",
    anthemName: "Patriots of Micronesia",
    src: "https://www.navyband.navy.mil/music/anthems/micronesia-short.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
  },
  {
    iso: "MD",
    countryName: "Moldova",
    anthemName: "Limba noastră",
    src: "https://www.navyband.navy.mil/music/anthems/moldova.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Our Language",
  },
  {
    iso: "MC",
    countryName: "Monaco",
    anthemName: "Hymne Monégasque",
    src: "https://www.navyband.navy.mil/music/anthems/monaco.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Monégasque Anthem",
  },
  {
    iso: "MN",
    countryName: "Mongolia",
    anthemName: "Монгол Улсын төрийн дуулал",
    src: "https://nationalanthems.info/mn.mp3",
    attribution: {
      text: "nationalanthems.info",
      href: "https://nationalanthems.info/mn.htm",
    },
    translatedName: "National anthem of Mongolia",
  },
  {
    iso: "ME",
    countryName: "Montenegro",
    anthemName: "Oj, svijetla majska zoro",
    src: "https://www.navyband.navy.mil/music/anthems/montenegro.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "O Bright Dawn of May",
  },
  {
    iso: "MA",
    countryName: "Morocco",
    anthemName: "النشيد الوطني المغربي",
    src: "https://www.navyband.navy.mil/music/anthems/morocco.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "National Anthem of Morocco",
  },
  {
    iso: "MZ",
    countryName: "Mozambique",
    anthemName: "Pátria Amada",
    src: "https://www.navyband.navy.mil/music/anthems/mozambique.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Beloved Homeland",
  },
  {
    iso: "MM",
    countryName: "Myanmar",
    anthemName: "ကမ္ဘာမကျေ",
    src: "https://www.navyband.navy.mil/music/anthems/myanmar.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Till the End of the World",
  },
  {
    iso: "NA",
    countryName: "Namibia",
    anthemName: "Namibia, Land of the Brave",
    src: "https://www.navyband.navy.mil/music/anthems/namibia.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
  },
  {
    iso: "NR",
    countryName: "Nauru",
    anthemName: "Nauru Bwiema",
    src: "https://web.archive.org.au/awa/20231218155154mp_/https://www.navy.gov.au/sites/default/files/audio/Nauru.mp3",
    attribution: {
      text: "Royal Australian Navy Band",
      href: "https://webarchive.nla.gov.au/awa/20231218155154/https://www.navy.gov.au/global-anthems",
    },
    translatedName: "Nauru, our homeland",
  },
  {
    iso: "NP",
    countryName: "Nepal",
    anthemName: "सयौँ थुँगा फूलका",
    src: "https://www.navyband.navy.mil/music/anthems/nepal.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Made of Hundreds of Flowers",
  },
  {
    iso: "NL",
    countryName: "Netherlands",
    anthemName: "Wilhelmus",
    src: "https://www.navyband.navy.mil/music/anthems/netherlands.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
  },
  {
    iso: "NZ",
    countryName: "New Zealand",
    anthemName: "God Defend New Zealand",
    src: "https://www.navyband.navy.mil/music/anthems/new-zealand-god-defend-new-zealand.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
  },
  {
    iso: "NI",
    countryName: "Nicaragua",
    anthemName: "Salve a ti, Nicaragua",
    src: "https://www.navyband.navy.mil/music/anthems/nicaragua.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Hail to thee, Nicaragua",
  },
  {
    iso: "NE",
    countryName: "Niger",
    anthemName: "L'Honneur de la Patrie",
    src: "https://nationalanthems.info/ne.mp3",
    attribution: {
      text: "Keith Terrett / nationalanthems.info",
      href: "https://nationalanthems.info/ne.htm",
    },
    translatedName: "The Honor of the Fatherland",
  },
  {
    iso: "NG",
    countryName: "Nigeria",
    anthemName: "Nigeria, We Hail Thee",
    src: "https://nationalanthems.info/ng.mp3",
    attribution: {
      text: "Keith Terrett / nationalanthems.info",
      href: "https://nationalanthems.info/ng.htm",
    },
  },
  {
    iso: "KP",
    countryName: "North Korea",
    anthemName: "애국가",
    src: "https://web.archive.org.au/awa/20231218155154mp_/https://www.navy.gov.au/sites/default/files/audio/North_Korea.mp3",
    attribution: {
      text: "Royal Australian Navy Band",
      href: "https://webarchive.nla.gov.au/awa/20231218155154/https://www.navy.gov.au/global-anthems",
    },
    translatedName: "Patriotic Song",
  },
  {
    iso: "MK",
    countryName: "North Macedonia",
    anthemName: "Денес над Македонија",
    src: "https://www.navyband.navy.mil/music/anthems/macedonia.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Today over Macedonia",
  },
  {
    iso: "NO",
    countryName: "Norway",
    anthemName: "Ja, vi elsker dette landet",
    src: "https://www.navyband.navy.mil/music/anthems/norway.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Yes, We Love This Country",
  },
  {
    iso: "OM",
    countryName: "Oman",
    anthemName: "نشيد السلام السلطاني",
    src: "https://www.navyband.navy.mil/music/anthems/oman.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "The Salute of the Sultan",
  },
  {
    iso: "PK",
    countryName: "Pakistan",
    anthemName: "قومی ترانہ",
    src: "https://www.navyband.navy.mil/music/anthems/pakistan.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "National Anthem of Pakistan",
  },
  {
    iso: "PW",
    countryName: "Palau",
    anthemName: "Belau rekid",
    src: "http://www.navyband.navy.mil/music/anthems/palau-belau.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Our Palau",
  },
  {
    iso: "PS",
    countryName: "Palestine",
    anthemName: "فِدَائِ",
    src: "https://web.archive.org.au/awa/20231218155154mp_/https://www.navy.gov.au/sites/default/files/audio/Palestine.mp3",
    attribution: {
      text: "Royal Australian Navy Band",
      href: "https://webarchive.nla.gov.au/awa/20231218155154/https://www.navy.gov.au/global-anthems",
    },
    translatedName: "Fedayeen Warrior",
  },
  {
    iso: "PA",
    countryName: "Panama",
    anthemName: "Himno Istmeño",
    src: "https://www.navyband.navy.mil/music/anthems/panama.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "National anthem of Panama",
  },
  {
    iso: "PG",
    countryName: "Papua New Guinea",
    anthemName: "O Arise, All You Sons",
    src: "https://www.navyband.navy.mil/music/anthems/papua-new-guinea.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
  },
  {
    iso: "PY",
    countryName: "Paraguay",
    anthemName: "Himno Nacional Paraguayo",
    src: "https://upload.wikimedia.org/wikipedia/commons/a/a6/Paraguayan_National_Anthem.oga",
    attribution: {
      text: "United States Navy Band",
      href: "https://commons.wikimedia.org/wiki/File:Paraguayan_National_Anthem.oga",
    },
    translatedName: "Paraguayan National Anthem",
  },
  {
    iso: "PE",
    countryName: "Peru",
    anthemName: "Himno Nacional del Perú",
    src: "https://www.navyband.navy.mil/music/anthems/peru.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "National Anthem of Peru",
  },
  {
    iso: "PH",
    countryName: "Philippines",
    anthemName: "Lupang Hinirang",
    src: "https://upload.wikimedia.org/wikipedia/commons/5/59/Philippine_National_Anthem%2C_the_Lupang_Hinirang%2C_Himno_Nacional_Filipino_Unknown_Artist.ogg",
    attribution: {
      text: "Department of Education, Government of the Philippines",
      href: "https://commons.wikimedia.org/wiki/File:Philippine_National_Anthem,_the_Lupang_Hinirang,_Himno_Nacional_Filipino_Unknown_Artist.ogg",
    },
    translatedName: "Chosen Land",
  },
  {
    iso: "PL",
    countryName: "Poland",
    anthemName: "Jeszcze Polska nie zginęła",
    src: "https://www.navyband.navy.mil/music/anthems/poland.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Poland Is Not Yet Lost",
  },
  {
    iso: "PT",
    countryName: "Portugal",
    anthemName: "A Portuguesa",
    src: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Hino_Nacional_da_Republica_Portuguesa.ogg",
    attribution: {
      text: "President of the Portugese Republic",
      href: "https://commons.wikimedia.org/wiki/File:Hino_Nacional_da_Republica_Portuguesa.ogg",
    },
    translatedName: "The Portuguese",
  },
  {
    iso: "QA",
    countryName: "Qatar",
    anthemName: "السلام الأميري",
    src: "https://www.navyband.navy.mil/music/anthems/qatar.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Peace to the Amir",
  },
  {
    iso: "CG",
    countryName: "Republic of the Congo",
    anthemName: "La Congolaise",
    src: "https://upload.wikimedia.org/wikipedia/commons/d/dc/National_anthem_of_the_Republic_of_the_Congo.oga",
    attribution: {
      text: "United States Navy Band",
      href: "https://commons.wikimedia.org/wiki/File:National_anthem_of_the_Republic_of_the_Congo.oga",
    },
    translatedName: "The Congolese",
  },
  {
    iso: "RO",
    countryName: "Romania",
    anthemName: "Deșteaptă-te, române!",
    src: "https://www.navyband.navy.mil/music/anthems/romania.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Awaken Thee, Romanian!",
  },
  {
    iso: "RU",
    countryName: "Russia",
    anthemName: "Госуда́рственный гимн Росси́йской Федера́ции",
    src: "https://upload.wikimedia.org/wikipedia/commons/4/41/National_Anthem_of_Russia_%282000%29%2C_instrumental%2C_one_verse.ogg",
    attribution: {
      text: "Presidential Orchestra of the Russian Federation",
      href: "https://commons.wikimedia.org/wiki/File:National_Anthem_of_Russia_(2000),_instrumental,_one_verse.ogg",
    },
    translatedName: "State Anthem of the Russian Federation",
  },
  {
    iso: "RW",
    countryName: "Rwanda",
    anthemName: "Rwanda Nziza",
    src: "https://www.navyband.navy.mil/music/anthems/rwanda.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Beautiful Rwanda",
  },
  {
    iso: "KN",
    countryName: "Saint Kitts and Nevis",
    anthemName: "O Land of Beauty!",
    src: "https://www.navyband.navy.mil/music/anthems/st-kitts-and-nevis.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
  },
  {
    iso: "LC",
    countryName: "Saint Lucia",
    anthemName: "Sons and Daughters of Saint Lucia",
    src: "https://upload.wikimedia.org/wikipedia/commons/6/6f/National_Anthem_of_Saint_Lucia.ogg",
    attribution: {
      text: "United States Navy Band",
      href: "https://commons.wikimedia.org/wiki/File:National_Anthem_of_Saint_Lucia.ogg",
    },
  },
  {
    iso: "VC",
    countryName: "Saint Vincent and the Grenadines",
    anthemName: "Saint Vincent, Land so Beautiful",
    src: "https://upload.wikimedia.org/wikipedia/commons/b/b3/National_anthem_of_Saint_Vincent_and_the_Grenadines%2C_performed_by_the_United_States_Navy_Band.oga",
    attribution: {
      text: "United States Navy Band",
      href: "https://commons.wikimedia.org/wiki/File:National_anthem_of_Saint_Vincent_and_the_Grenadines,_performed_by_the_United_States_Navy_Band.oga",
    },
  },
  {
    iso: "WS",
    countryName: "Samoa",
    anthemName: "O Le Fuʻa o Le Saʻolotoga o Sāmoa",
    src: "https://web.archive.org.au/awa/20231218155154mp_/https://www.navy.gov.au/sites/default/files/audio/Samoa.mp3",
    attribution: {
      text: "Royal Australian Navy Band",
      href: "https://webarchive.nla.gov.au/awa/20231218155154/https://www.navy.gov.au/global-anthems",
    },
    translatedName: "The Banner of Freedom",
  },
  {
    iso: "SM",
    countryName: "San Marino",
    anthemName: "Inno Nazionale della Repubblica di San Marino",
    src: "https://nationalanthems.info/sm.mp3",
    attribution: {
      text: "nationalanthems.info",
      href: "https://nationalanthems.info/sm.htm",
    },
    translatedName: "National Anthem of the Republic of San Marino",
  },
  {
    iso: "ST",
    countryName: "Sao Tome and Principe",
    anthemName: "Independência total",
    src: "https://www.navyband.navy.mil/music/anthems/sao-tome-and-principe.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Total Independence",
  },
  {
    iso: "SA",
    countryName: "Saudi Arabia",
    anthemName: "النشيد الوطني السعودي",
    src: "https://www.navyband.navy.mil/music/anthems/saudi-arabia.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Chant of the Saudi Nation",
  },
  {
    iso: "SN",
    countryName: "Senegal",
    anthemName: "Le Lion rouge",
    src: "https://www.navyband.navy.mil/music/anthems/senegal.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "The Red Lion",
  },
  {
    iso: "RS",
    countryName: "Serbia",
    anthemName: "Боже правде",
    src: "https://www.navyband.navy.mil/music/anthems/serbia.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "God of Justice",
  },
  {
    iso: "SC",
    countryName: "Seychelles",
    anthemName: "Koste Seselwa",
    src: "https://www.navyband.navy.mil/music/anthems/seychelles.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Join together all Seychellois",
  },
  {
    iso: "SL",
    countryName: "Sierra Leone",
    anthemName: "High We Exalt Thee, Realm of the Free",
    src: "https://www.navyband.navy.mil/music/anthems/sierra-leone.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
  },
  {
    iso: "SG",
    countryName: "Singapore",
    anthemName: "Majulah Singapura",
    src: "https://www.navyband.navy.mil/music/anthems/singapore.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Onward Singapore",
  },
  {
    iso: "SK",
    countryName: "Slovakia",
    anthemName: "Nad Tatrou sa blýska",
    src: "https://upload.wikimedia.org/wikipedia/commons/2/2b/Lightning_over_the_Tatras.ogg",
    attribution: {
      text: "Government of the Slovak Republic",
      href: "https://commons.wikimedia.org/wiki/File:Lightning_over_the_Tatras.ogg",
    },
    translatedName: "Lightning Over the Tatras",
  },
  {
    iso: "SI",
    countryName: "Slovenia",
    anthemName: "Zdravljica",
    src: "https://www.navyband.navy.mil/music/anthems/slovenia.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Toast",
  },
  {
    iso: "SB",
    countryName: "Solomon Islands",
    anthemName: "God Save Our Solomon Islands",
    src: "https://web.archive.org.au/awa/20231218155154mp_/https://www.navy.gov.au/sites/default/files/audio/Solomon_Islands.mp3",
    attribution: {
      text: "Royal Australian Navy Band",
      href: "https://webarchive.nla.gov.au/awa/20231218155154/https://www.navy.gov.au/global-anthems",
    },
  },
  {
    iso: "SO",
    countryName: "Somalia",
    anthemName: "Qolobaa Calankeed",
    src: "https://www.navyband.navy.mil/music/anthems/somalia.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Every nation has its own flag",
  },
  {
    iso: "ZA",
    countryName: "South Africa",
    anthemName: "National Anthem of South Africa",
    src: "https://www.navyband.navy.mil/music/anthems/south-africa.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
  },
  {
    iso: "KR",
    countryName: "South Korea",
    anthemName: "애국가",
    src: "https://upload.wikimedia.org/wikipedia/commons/5/5e/National_Anthem_of_Republic_of_Korea_2018_Orchestral_%281_Verse_Version%29.ogg",
    attribution: {
      text: "Seoul Philharmonic Orchestra",
      href: "https://commons.wikimedia.org/wiki/File:National_Anthem_of_Republic_of_Korea_2018_Orchestral_(1_Verse_Version).ogg",
    },
    translatedName: "Patriotic Song",
  },
  {
    iso: "SS",
    countryName: "South Sudan",
    anthemName: "South Sudan Oyee!",
    src: "https://www.navyband.navy.mil/music/anthems/south-sudan.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "South Sudan Hurrah!",
  },
  {
    iso: "ES",
    countryName: "Spain",
    anthemName: "Marcha Real",
    src: "https://upload.wikimedia.org/wikipedia/commons/8/81/Himno_Nacional_de_Espa%C3%B1a.ogg",
    attribution: {
      text: "Marcha Real, Gobierno de España",
      href: "https://commons.wikimedia.org/wiki/File:Himno_Nacional_de_Espa%C3%B1a.ogg",
    },
    translatedName: "Royal March",
  },
  {
    iso: "LK",
    countryName: "Sri Lanka",
    anthemName: "ශ්‍රී ලංකා මාතා",
    src: "https://www.navyband.navy.mil/music/anthems/sri-lanka.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Mother Sri Lanka",
  },
  {
    iso: "SD",
    countryName: "Sudan",
    anthemName: "نحن جند الله جند الوطن",
    src: "https://www.navyband.navy.mil/music/anthems/sudan.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "We are Soldiers of God, Soldiers of the Homeland",
  },
  {
    iso: "SR",
    countryName: "Suriname",
    anthemName: "God zij met ons Suriname",
    src: "https://upload.wikimedia.org/wikipedia/commons/d/d9/Surinamese_national_anthem%2C_performed_by_the_U.S._Navy_Band.ogg",
    attribution: {
      text: "United States Navy Band",
      href: "https://commons.wikimedia.org/wiki/File:Surinamese_national_anthem,_performed_by_the_U.S._Navy_Band.ogg",
    },
    translatedName: "God be with our Suriname",
  },
  {
    iso: "SE",
    countryName: "Sweden",
    anthemName: "Du gamla, du fria",
    src: "https://www.navyband.navy.mil/music/anthems/sweden.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "You ancient, you free",
  },
  {
    iso: "CH",
    countryName: "Switzerland",
    anthemName: "Schweizerpsalm",
    src: "https://www.navyband.navy.mil/music/anthems/switzerland.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Swiss Psalm",
  },
  {
    iso: "TW",
    countryName: "Taiwan",
    anthemName: "中華民國國歌",
    src: "https://upload.wikimedia.org/wikipedia/commons/b/be/National_anthem_of_the_Republic_of_China_%28Taiwan%29_%E4%B8%AD%E8%8F%AF%E6%B0%91%E5%9C%8B%E5%9C%8B%E6%AD%8C%28%E6%BC%94%E5%A5%8F%E7%89%88%29.ogg",
    attribution: {
      text: "Office of the President of the Republic of China",
      href: "https://commons.wikimedia.org/wiki/File:National_anthem_of_the_Republic_of_China_(Taiwan)_%E4%B8%AD%E8%8F%AF%E6%B0%91%E5%9C%8B%E5%9C%8B%E6%AD%8C(%E6%BC%94%E5%A5%8F%E7%89%88).ogg",
    },
    translatedName: "National Anthem of the Republic of China",
  },
  {
    iso: "TJ",
    countryName: "Tajikistan",
    anthemName: "Суруди Миллӣ",
    src: "https://www.navyband.navy.mil/music/anthems/tajikistan.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "National Anthem",
  },
  {
    iso: "TZ",
    countryName: "Tanzania",
    anthemName: "Mungu ibariki Afrika",
    src: "https://www.navyband.navy.mil/music/anthems/tanzania.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "God bless Africa",
  },
  {
    iso: "TH",
    countryName: "Thailand",
    anthemName: "เพลงชาติไทย",
    src: "https://upload.wikimedia.org/wikipedia/commons/f/f3/Thai_National_Anthem_-_US_Navy_Band.ogg",
    attribution: {
      text: "United States Navy Band",
      href: "https://commons.wikimedia.org/wiki/File:Thai_National_Anthem_-_US_Navy_Band.ogg",
    },
    translatedName: "Thai National Anthem",
  },
  {
    iso: "BS",
    countryName: "The Bahamas",
    anthemName: "March On, Bahamaland",
    src: "https://www.navyband.navy.mil/music/anthems/bahamas.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
  },
  {
    iso: "GM",
    countryName: "The Gambia",
    anthemName: "For The Gambia Our Homeland",
    src: "https://www.navyband.navy.mil/music/anthems/gambia.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
  },
  {
    iso: "TL",
    countryName: "Timor-Leste",
    anthemName: "Pátria",
    src: "https://www.navyband.navy.mil/music/anthems/east-timor.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Fatherland",
  },
  {
    iso: "TG",
    countryName: "Togo",
    anthemName: "Terre de nos aïeux",
    src: "https://www.navyband.navy.mil/music/anthems/togo.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Land of our forefathers",
  },
  {
    iso: "TO",
    countryName: "Tonga",
    anthemName: "Ko e fasi ʻo e tuʻi ʻo e ʻOtu Tonga",
    src: "https://web.archive.org.au/awa/20231218155154mp_/https://www.navy.gov.au/sites/default/files/audio/Tonga.mp3",
    attribution: {
      text: "Royal Australian Navy Band",
      href: "https://webarchive.nla.gov.au/awa/20231218155154/https://www.navy.gov.au/global-anthems",
    },
    translatedName: "Song of the King of the Tongan Islands",
  },
  {
    iso: "TT",
    countryName: "Trinidad and Tobago",
    anthemName: "Forged from the Love of Liberty",
    src: "https://www.navyband.navy.mil/music/anthems/trinidad-and-tobago.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
  },
  {
    iso: "TN",
    countryName: "Tunisia",
    anthemName: "حماة الحمى",
    src: "https://www.navyband.navy.mil/music/anthems/tunisia.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Defenders of the Homeland",
  },
  {
    iso: "TR",
    countryName: "Turkey",
    anthemName: "İstiklal Marşı",
    src: "https://www.navyband.navy.mil/music/anthems/turkey.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Independence March",
  },
  {
    iso: "TM",
    countryName: "Turkmenistan",
    anthemName: "Garaşsyz, Bitarap Türkmenistanyň Döwlet Gimni",
    src: "https://www.navyband.navy.mil/music/anthems/turkmenistan.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "State Anthem of Independent, Neutral Turkmenistan",
  },
  {
    iso: "TV",
    countryName: "Tuvalu",
    anthemName: "Tuvalu mo te Atua",
    src: "https://nationalanthems.info/tv.mp3",
    attribution: {
      text: "Keith Terrett / nationalanthems.info",
      href: "https://nationalanthems.info/tv.htm",
    },
    translatedName: "Tuvalu for the Almighty",
  },
  {
    iso: "UG",
    countryName: "Uganda",
    anthemName: "Oh Uganda, Land of Beauty",
    src: "https://www.navyband.navy.mil/music/anthems/uganda.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
  },
  {
    iso: "UA",
    countryName: "Ukraine",
    anthemName: "Державний гімн України",
    src: "https://www.navyband.navy.mil/music/anthems/ukraine.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "State Anthem of Ukraine",
  },
  {
    iso: "AE",
    countryName: "United Arab Emirates",
    anthemName: "النشيد الوطني الإماراتي",
    src: "https://www.navyband.navy.mil/music/anthems/united-arab-emirates.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Long Live my Nation",
  },
  {
    iso: "GB",
    countryName: "United Kingdom",
    anthemName: "God Save the King",
    src: "https://www.navyband.navy.mil/music/anthems/united-kingdom.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
  },
  {
    iso: "US",
    countryName: "United States",
    anthemName: "The Star-Spangled Banner",
    src: "https://www.navyband.navy.mil/music/anthems/united-states.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
  },
  {
    iso: "UY",
    countryName: "Uruguay",
    anthemName: "Himno Nacional de Uruguay",
    src: "https://upload.wikimedia.org/wikipedia/commons/a/a1/United_States_Navy_Band_-_National_Anthem_of_Uruguay_%28short_with_intro%29.ogg",
    attribution: {
      text: "United States Navy Band",
      href: "https://commons.wikimedia.org/wiki/File:United_States_Navy_Band_-_National_Anthem_of_Uruguay_(short_with_intro).ogg",
    },
    translatedName: "National Anthem of Uruguay",
  },
  {
    iso: "UZ",
    countryName: "Uzbekistan",
    anthemName: "Oʻzbekiston Respublikasining Davlat Madhiyasi",
    src: "https://www.navyband.navy.mil/music/anthems/uzbekistan.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "State Anthem of the Republic of Uzbekistan",
  },
  {
    iso: "VU",
    countryName: "Vanuatu",
    anthemName: "Yumi, Yumi, Yumi",
    src: "https://www.navyband.navy.mil/music/anthems/vanuatu.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "We are, We are, We are",
  },
  {
    iso: "VA",
    countryName: "Vatican City",
    anthemName: "Inno e Marcia Pontificale",
    src: "https://www.navyband.navy.mil/music/anthems/holy-see.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Pontifical Anthem and March",
  },
  {
    iso: "VE",
    countryName: "Venezuela",
    anthemName: "Gloria al Bravo Pueblo",
    src: "https://www.navyband.navy.mil/music/anthems/venezuela.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "Glory to the Brave People",
  },
  {
    iso: "VN",
    countryName: "Vietnam",
    anthemName: "Tiến Quân Ca",
    src: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Quoc_ca_Viet_Nam.ogg",
    attribution: {
      text: "Government of Vietnam",
      href: "https://commons.wikimedia.org/wiki/File:Quoc_ca_Viet_Nam.ogg",
    },
    translatedName: "The Song of the Marching Troops",
  },
  {
    iso: "YE",
    countryName: "Yemen",
    anthemName: "الجمهورية المتحدة",
    src: "https://www.navyband.navy.mil/music/anthems/yemen.mp3",
    attribution: {
      text: "United States Navy Band",
      href: "https://www.navyband.navy.mil/media/ceremonial",
    },
    translatedName: "United Republic",
  },
  {
    iso: "ZW",
    countryName: "Zimbabwe",
    anthemName: "Ngaikomborerwe Nyika yeZimbabwe",
    src: "https://web.archive.org.au/awa/20231218155154mp_/https://www.navy.gov.au/sites/default/files/audio/Zimbabwe.mp3",
    attribution: {
      text: "Royal Australian Navy Band",
      href: "https://webarchive.nla.gov.au/awa/20231218155154/https://www.navy.gov.au/global-anthems",
    },
    translatedName: "Blessed be the land of Zimbabwe",
  },
];
